import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  const teams = [
    {
      name: "Stade Tunisien",
      founded: 1948,
      city: "Tunis",
      points: 38,
      position: 8,
      matchesPlayed: 28,
      wins: 10,
      draws: 8,
      losses: 10,
      goalsFor: 28,
      goalsAgainst: 28,
      goalDifference: 0,
      players: [
        { name: "Mohamed Ali Ben Romdhane", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
        { name: "Yassine Meriah", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
        { name: "Anice Badri", nationality: "Tunisia", age: 32, position: "Forward", goals: 15, assists: 10 },
        { name: "Fedi Ben Choug", nationality: "Tunisia", age: 24, position: "Midfielder", goals: 3, assists: 4 },
        { name: "Mohamed Ali Ben Hammouda", nationality: "Tunisia", age: 24, position: "Forward", goals: 10, assists: 5 },
        { name: "Oussama Darragi", nationality: "Tunisia", age: 34, position: "Midfielder", goals: 5, assists: 7 },
        { name: "Ahmed Akaichi", nationality: "Tunisia", age: 31, position: "Forward", goals: 8, assists: 4 },
      ],
      homeMatches: [
        { opponent: "CA Bizertin", date: new Date("2022-01-15"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "Espérance Sportive de Tunis", date: new Date("2022-02-20"), goalsFor: 1, goalsAgainst: 1 },
        { opponent: "Étoile Sportive du Sahel", date: new Date("2022-03-10"), goalsFor: 3, goalsAgainst: 0 },
      ],
      awayMatches: [
        { opponent: "Club Africain", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "Club Sportif Sfaxien", date: new Date("2022-02-27"), goalsFor: 0, goalsAgainst: 3 },
        { opponent: "US Monastir", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
      ],
    },
    {
      name: "CA Bizertin",
      founded: 1928,
      city: "Bizerte",
      points: 28,
      position: 12,
      matchesPlayed: 28,
      wins: 7,
      draws: 7,
      losses: 14,
      goalsFor: 28,
      goalsAgainst: 38,
      goalDifference: -10,
      players: [
        { name: "Ahmed Khalil", nationality: "Tunisia", age: 25, position: "Midfielder", goals: 5, assists: 3 },
        { name: "Hamza Mathlouthi", nationality: "Tunisia", age: 29, position: "Defender", goals: 1, assists: 2 },
        { name: "Yassine Meriah", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
        { name: "Anice Badri", nationality: "Tunisia", age: 32, position: "Forward", goals: 15, assists: 10 },
        { name: "Mohamed Ali Ben Romdhane", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
        { name: "Yassine Chikhaoui", nationality: "Tunisia", age: 36, position: "Midfielder", goals: 12, assists: 8 },
        { name: "Mohamed Amine Ben Amor", nationality: "Tunisia", age: 30, position: "Midfielder", goals: 5, assists: 3 },
      ],
      homeMatches: [
        { opponent: "Stade Tunisien", date: new Date("2022-01-15"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "Espérance Sportive de Tunis", date: new Date("2022-02-20"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "Étoile Sportive du Sahel", date: new Date("2022-03-10"), goalsFor: 0, goalsAgainst: 3 },
      ],
      awayMatches: [
        { opponent: "Club Africain", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "Club Sportif Sfaxien", date: new Date("2022-02-27"), goalsFor: 0, goalsAgainst: 3 },
        { opponent: "US Monastir", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
      ],
    },
    {
      name: "Espérance Sportive de Tunis",
      founded: 1919,
      city: "Tunis",
      points: 70,
      position: 1,
      matchesPlayed: 28,
      wins: 22,
      draws: 4,
      losses: 2,
      goalsFor: 60,
      goalsAgainst: 15,
      goalDifference: 45,
      players: [
        { name: "Anice Badri", nationality: "Tunisia", age: 32, position: "Forward", goals: 15, assists: 10 },
        { name: "Mohamed Ali Ben Romdhane", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
        { name: "Yassine Meriah", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
        { name: "Fedi Ben Choug", nationality: "Tunisia", age: 24, position: "Midfielder", goals: 3, assists: 4 },
        { name: "Mohamed Ali Ben Hammouda", nationality: "Tunisia", age: 24, position: "Forward", goals: 10, assists: 5 },
        { name: "Oussama Darragi", nationality: "Tunisia", age: 34, position: "Midfielder", goals: 5, assists: 7 },
        { name: "Ahmed Akaichi", nationality: "Tunisia", age: 31, position: "Forward", goals: 8, assists: 4 },
      ],
      homeMatches: [
        { opponent: "Stade Tunisien", date: new Date("2022-01-15"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "CA Bizertin", date: new Date("2022-02-20"), goalsFor: 1, goalsAgainst: 1 },
        { opponent: "Étoile Sportive du Sahel", date: new Date("2022-03-10"), goalsFor: 3, goalsAgainst: 0 },
      ],
      awayMatches: [
        { opponent: "Club Africain", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "Club Sportif Sfaxien", date: new Date("2022-02-27"), goalsFor: 0, goalsAgainst: 3 },
        { opponent: "US Monastir", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
      ],
    },
    {
      name: "Étoile Sportive du Sahel",
      founded: 1925,
      city: "Sousse",
      points: 62,
      position: 2,
      matchesPlayed: 28,
      wins: 19,
      draws: 5,
      losses: 4,
      goalsFor: 50,
      goalsAgainst: 20,
      goalDifference: 30,
      players: [
        { name: "Yassine Chikhaoui", nationality: "Tunisia", age: 36, position: "Midfielder", goals: 12, assists: 8 },
        { name: "Mohamed Amine Ben Amor", nationality: "Tunisia", age: 30, position: "Midfielder", goals: 5, assists: 3 },
        { name: "Seifeddine Jaziri", nationality: "Tunisia", age: 29, position: "Forward", goals: 18, assists: 7 },
        { name: "Hamza Lahmar", nationality: "Tunisia", age: 31, position: "Midfielder", goals: 8, assists: 10 },
        { name: "Firas Chaouat", nationality: "Tunisia", age: 25, position: "Forward", goals: 15, assists: 10 },
        { name: "Houssem Tabboubi", nationality: "Tunisia", age: 27, position: "Midfielder", goals: 5, assists: 3 },
        { name: "Aymen Ben Mohamed", nationality: "Tunisia", age: 28, position: "Defender", goals: 1, assists: 2 },
      ],
      homeMatches: [
        { opponent: "Stade Tunisien", date: new Date("2022-01-15"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "CA Bizertin", date: new Date("2022-02-20"), goalsFor: 1, goalsAgainst: 1 },
        { opponent: "Espérance Sportive de Tunis", date: new Date("2022-03-10"), goalsFor: 3, goalsAgainst: 0 },
      ],
      awayMatches: [
        { opponent: "Club Africain", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "Club Sportif Sfaxien", date: new Date("2022-02-27"), goalsFor: 0, goalsAgainst: 3 },
        { opponent: "US Monastir", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
      ],
    },
    {
      name: "Club Africain",
      founded: 1920,
      city: "Tunis",
      points: 58,
      position: 3,
      matchesPlayed: 28,
      wins: 18,
      draws: 4,
      losses: 6,
      goalsFor: 45,
      goalsAgainst: 20,
      goalDifference: 25,
      players: [
        { name: "Seifeddine Jaziri", nationality: "Tunisia", age: 29, position: "Forward", goals: 18, assists: 7 },
        { name: "Hamza Lahmar", nationality: "Tunisia", age: 31, position: "Midfielder", goals: 8, assists: 10 },
        { name: "Firas Chaouat", nationality: "Tunisia", age: 25, position: "Forward", goals: 15, assists: 10 },
        { name: "Houssem Tabboubi", nationality: "Tunisia", age: 27, position: "Midfielder", goals: 5, assists: 3 },
        { name: "Aymen Ben Mohamed", nationality: "Tunisia", age: 28, position: "Defender", goals: 1, assists: 2 },
        { name: "Mohamed Ali Ben Romdhane", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
        { name: "Yassine Meriah", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
      ],
      homeMatches: [
        { opponent: "Stade Tunisien", date: new Date("2022-01-15"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "CA Bizertin", date: new Date("2022-02-20"), goalsFor: 1, goalsAgainst: 1 },
        { opponent: "Espérance Sportive de Tunis", date: new Date("2022-03-10"), goalsFor: 3, goalsAgainst: 0 },
      ],
      awayMatches: [
        { opponent: "Étoile Sportive du Sahel", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "Club Sportif Sfaxien", date: new Date("2022-02-27"), goalsFor: 0, goalsAgainst: 3 },
        { opponent: "US Monastir", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
      ],
    },
    {
      name: "Club Sportif Sfaxien",
      founded: 1928,
      city: "Sfax",
      points: 55,
      position: 4,
      matchesPlayed: 28,
      wins: 17,
      draws: 4,
      losses: 7,
      goalsFor: 40,
      goalsAgainst: 20,
      goalDifference: 20,
      players: [
        { name: "Firas Chaouat", nationality: "Tunisia", age: 25, position: "Forward", goals: 15, assists: 10 },
        { name: "Aymen Harzi", nationality: "Tunisia", age: 27, position: "Midfielder", goals: 5, assists: 7 },
        { name: "Mohamed Ali Ben Romdhane", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
        { name: "Yassine Meriah", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
        { name: "Anice Badri", nationality: "Tunisia", age: 32, position: "Forward", goals: 15, assists: 10 },
        { name: "Mohamed Ali Ben Romdhane", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
        { name: "Yassine Chikhaoui", nationality: "Tunisia", age: 36, position: "Midfielder", goals: 12, assists: 8 },
      ],
      homeMatches: [
        { opponent: "Stade Tunisien", date: new Date("2022-01-15"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "CA Bizertin", date: new Date("2022-02-20"), goalsFor: 1, goalsAgainst: 1 },
        { opponent: "Espérance Sportive de Tunis", date: new Date("2022-03-10"), goalsFor: 3, goalsAgainst: 0 },
      ],
      awayMatches: [
        { opponent: "Étoile Sportive du Sahel", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "Club Africain", date: new Date("2022-02-27"), goalsFor: 0, goalsAgainst: 3 },
        { opponent: "US Monastir", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
      ],
    },
    {
      name: "US Monastir",
      founded: 1923,
      city: "Monastir",
      points: 52,
      position: 5,
      matchesPlayed: 28,
      wins: 15,
      draws: 7,
      losses: 6,
      goalsFor: 35,
      goalsAgainst: 20,
      goalDifference: 15,
      players: [
        { name: "Yassine Amri", nationality: "Tunisia", age: 24, position: "Midfielder", goals: 12, assists: 8 },
        { name: "Bilel Ifa", nationality: "Tunisia", age: 31, position: "Defender", goals: 3, assists: 2 },
        { name: "Mohamed Ali Ben Romdhane", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
        { name: "Yassine Meriah", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
        { name: "Anice Badri", nationality: "Tunisia", age: 32, position: "Forward", goals: 15, assists: 10 },
        { name: "Yassine Chikhaoui", nationality: "Tunisia", age: 36, position: "Midfielder", goals: 12, assists: 8 },
        { name: "Mohamed Amine Ben Amor", nationality: "Tunisia", age: 30, position: "Midfielder", goals: 5, assists: 3 },
        { name: "Seifeddine Jaziri", nationality: "Tunisia", age: 29, position: "Forward", goals: 18, assists: 7 },
        { name: "Hamza Lahmar", nationality: "Tunisia", age: 31, position: "Midfielder", goals: 8, assists: 10 },
        { name: "Firas Chaouat", nationality: "Tunisia", age: 25, position: "Forward", goals: 15, assists: 10 },
        { name: "Houssem Tabboubi", nationality: "Tunisia", age: 27, position: "Midfielder", goals: 5, assists: 3 },
      ],
      homeMatches: [
        { opponent: "US Ben Guerdane", date: new Date("2022-01-15"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "Olympique de Béja", date: new Date("2022-02-20"), goalsFor: 1, goalsAgainst: 1 },
        { opponent: "ES Métlaoui", date: new Date("2022-03-10"), goalsFor: 3, goalsAgainst: 0 },
      ],
      awayMatches: [
        { opponent: "CS Hammam-Lif", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "AS Rejiche", date: new Date("2022-02-27"), goalsFor: 0, goalsAgainst: 3 },
        { opponent: "Stade Tunisien", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
      ],
    },
    {
      name: "US Ben Guerdane",
      founded: 1936,
      city: "Ben Guerdane",
      points: 48,
      position: 6,
      matchesPlayed: 28,
      wins: 14,
      draws: 6,
      losses: 8,
      goalsFor: 30,
      goalsAgainst: 20,
      goalDifference: 10,
      players: [
        { name: "Aymen Sfaxi", nationality: "Tunisia", age: 26, position: "Forward", goals: 10, assists: 5 },
        { name: "Mohamed Ali Jouini", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
        { name: "Mohamed Ali Ben Romdhane", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
        { name: "Yassine Meriah", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
        { name: "Anice Badri", nationality: "Tunisia", age: 32, position: "Forward", goals: 15, assists: 10 },
        { name: "Yassine Chikhaoui", nationality: "Tunisia", age: 36, position: "Midfielder", goals: 12, assists: 8 },
        { name: "Mohamed Amine Ben Amor", nationality: "Tunisia", age: 30, position: "Midfielder", goals: 5, assists: 3 },
        { name: "Seifeddine Jaziri", nationality: "Tunisia", age: 29, position: "Forward", goals: 18, assists: 7 },
        { name: "Hamza Lahmar", nationality: "Tunisia", age: 31, position: "Midfielder", goals: 8, assists: 10 },
        { name: "Firas Chaouat", nationality: "Tunisia", age: 25, position: "Forward", goals: 15, assists: 10 },
        { name: "Houssem Tabboubi", nationality: "Tunisia", age: 27, position: "Midfielder", goals: 5, assists: 3 },
      ],
      homeMatches: [
        { opponent: "Olympique de Béja", date: new Date("2022-01-15"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "ES Métlaoui", date: new Date("2022-02-20"), goalsFor: 1, goalsAgainst: 1 },
        { opponent: "CS Hammam-Lif", date: new Date("2022-03-10"), goalsFor: 3, goalsAgainst: 0 },
      ],
      awayMatches: [
        { opponent: "AS Rejiche", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "Stade Tunisien", date: new Date("2022-02-27"), goalsFor: 0, goalsAgainst: 3 },
        { opponent: "CA Bizertin", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
      ],
    },
    {
      name: "Olympique de Béja",
      founded: 1929,
      city: "Béja",
      points: 42,
      position: 7,
      matchesPlayed: 28,
      wins: 12,
      draws: 6,
      losses: 10,
      goalsFor: 28,
      goalsAgainst: 25,
      goalDifference: 3,
      players: [
        { name: "Mohamed Ali Ben Hammouda", nationality: "Tunisia", age: 24, position: "Forward", goals: 10, assists: 5 },
        { name: "Oussama Darragi", nationality: "Tunisia", age: 34, position: "Midfielder", goals: 5, assists: 7 },
        { name: "Mohamed Ali Ben Romdhane", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
        { name: "Yassine Meriah", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
        { name: "Anice Badri", nationality: "Tunisia", age: 32, position: "Forward", goals: 15, assists: 10 },
        { name: "Yassine Chikhaoui", nationality: "Tunisia", age: 36, position: "Midfielder", goals: 12, assists: 8 },
        { name: "Mohamed Amine Ben Amor", nationality: "Tunisia", age: 30, position: "Midfielder", goals: 5, assists: 3 },
        { name: "Seifeddine Jaziri", nationality: "Tunisia", age: 29, position: "Forward", goals: 18, assists: 7 },
        { name: "Hamza Lahmar", nationality: "Tunisia", age: 31, position: "Midfielder", goals: 8, assists: 10 },
        { name: "Firas Chaouat", nationality: "Tunisia", age: 25, position: "Forward", goals: 15, assists: 10 },
        { name: "Houssem Tabboubi", nationality: "Tunisia", age: 27, position: "Midfielder", goals: 5, assists: 3 },
      ],
      homeMatches: [
        { opponent: "ES Métlaoui", date: new Date("2022-01-15"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "CS Hammam-Lif", date: new Date("2022-02-20"), goalsFor: 1, goalsAgainst: 1 },
        { opponent: "AS Rejiche", date: new Date("2022-03-10"), goalsFor: 3, goalsAgainst: 0 },
      ],
      awayMatches: [
        { opponent: "Stade Tunisien", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "CA Bizertin", date: new Date("2022-02-27"), goalsFor: 0, goalsAgainst: 3 },
        { opponent: "Espérance Sportive de Tunis", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
      ],
    },
    {
      name: "ES Métlaoui",
      founded: 1956,
      city: "Métlaoui",
      points: 35,
      position: 9,
      matchesPlayed: 28,
      wins: 9,
      draws: 8,
      losses: 11,
      goalsFor: 25,
      goalsAgainst: 40,
      goalDifference: -15,
      players: [
        { name: "Ahmed Akaichi", nationality: "Tunisia", age: 31, position: "Forward", goals: 8, assists: 4 },
        { name: "Ali Machani", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 3 },
        { name: "Mohamed Ali Ben Romdhane", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
        { name: "Yassine Meriah", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
        { name: "Anice Badri", nationality: "Tunisia", age: 32, position: "Forward", goals: 15, assists: 10 },
        { name: "Yassine Chikhaoui", nationality: "Tunisia", age: 36, position: "Midfielder", goals: 12, assists: 8 },
        { name: "Mohamed Amine Ben Amor", nationality: "Tunisia", age: 30, position: "Midfielder", goals: 5, assists: 3 },
        { name: "Seifeddine Jaziri", nationality: "Tunisia", age: 29, position: "Forward", goals: 18, assists: 7 },
        { name: "Hamza Lahmar", nationality: "Tunisia", age: 31, position: "Midfielder", goals: 8, assists: 10 },
        { name: "Firas Chaouat", nationality: "Tunisia", age: 25, position: "Forward", goals: 15, assists: 10 },
        { name: "Houssem Tabboubi", nationality: "Tunisia", age: 27, position: "Midfielder", goals: 5, assists: 3 },
      ],
      homeMatches: [
        { opponent: "CS Hammam-Lif", date: new Date("2022-01-15"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "Olympique de Béja", date: new Date("2022-01-17"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "Stade Tunisien", date: new Date("2022-03-10"), goalsFor: 3, goalsAgainst: 0 },
      ],
      awayMatches: [
        { opponent: "CA Bizertin", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "Espérance Sportive de Tunis", date: new Date("2022-02-30"), goalsFor: 0, goalsAgainst: 3 },
        { opponent: "Étoile Sportive du Sahel", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
      ],
    },
    {
      name: "CS Hammam-Lif",
      founded: 1944,
      city: "Hammam-Lif",
      points: 32,
      position: 10,
      matchesPlayed: 28,
      wins: 8,
      draws: 8,
      losses: 12,
      goalsFor: 20,
      goalsAgainst: 30,
      goalDifference: -10,
      players: [
        { name: "Houssem Tabboubi", nationality: "Tunisia", age: 27, position: "Midfielder", goals: 5, assists: 3 },
        { name: "Aymen Ben Mohamed", nationality: "Tunisia", age: 28, position: "Defender", goals: 1, assists: 2 },
        { name: "Mohamed Ali Ben Romdhane", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
        { name: "Yassine Meriah", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
        { name: "Anice Badri", nationality: "Tunisia", age: 32, position: "Forward", goals: 15, assists: 10 },
        { name: "Yassine Chikhaoui", nationality: "Tunisia", age: 36, position: "Midfielder", goals: 12, assists: 8 },
        { name: "Mohamed Amine Ben Amor", nationality: "Tunisia", age: 30, position: "Midfielder", goals: 5, assists: 3 },
        { name: "Seifeddine Jaziri", nationality: "Tunisia", age: 29, position: "Forward", goals: 18, assists: 7 },
        { name: "Hamza Lahmar", nationality: "Tunisia", age: 31, position: "Midfielder", goals: 8, assists: 10 },
        { name: "Firas Chaouat", nationality: "Tunisia", age: 25, position: "Forward", goals: 15, assists: 10 },
      ],
      homeMatches: [
        { opponent: "ES Métlaoui", date: new Date("2022-01-15"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "AS Rejiche", date: new Date("2022-02-20"), goalsFor: 2, goalsAgainst: 1 },
        { opponent: "Stade Tunisien", date: new Date("2022-03-10"), goalsFor: 0, goalsAgainst: 3 },
      ],
      awayMatches: [
        { opponent: "CA Bizertin", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
        { opponent: "Espérance Sportive de Tunis", date: new Date("2022-02-27"), goalsFor: 0, goalsAgainst: 3 },
        { opponent: "Étoile Sportive du Sahel", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
      ],
    },
      {
        name: "AS Rejiche",
        founded: 1980,
        city: "Rejiche",
        points: 30,
        position: 11,
        matchesPlayed: 28,
        wins: 8,
        draws: 6,
        losses: 14,
        goalsFor: 18,
        goalsAgainst: 28,
        goalDifference: -10,
        players: [
          { name: "Mohamed Ali Ben Romdhan12", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
          { name: "Yassine Meriah12", nationality: "Tunisia", age: 28, position: "Defender", goals: 2, assists: 1 },
          { name: "Anice Badri12", nationality: "Tunisia", age: 32, position: "Forward", goals: 15, assists: 10 },
          { name: "Mohamed Ali Ben Romdhane12", nationality: "Tunisia", age: 23, position: "Midfielder", goals: 10, assists: 5 },
          { name: "Yassine Chikhaoui12", nationality: "Tunisia", age: 36, position: "Midfielder", goals: 12, assists: 8 },
          { name: "Mohamed Amine Ben Amor12", nationality: "Tunisia", age: 30, position: "Midfielder", goals: 5, assists: 3 },
          { name: "Seifeddine Jaziri12", nationality: "Tunisia", age: 29, position: "Forward", goals: 18, assists: 7 },
          { name: "Hamza Lahmar12", nationality: "Tunisia", age: 31, position: "Midfielder", goals: 8, assists: 10 },
          { name: "Firas Chaouat12", nationality: "Tunisia", age: 25, position: "Forward", goals: 15, assists: 10 },
          { name: "Houssem Tabboubi12", nationality: "Tunisia", age: 27, position: "Midfielder", goals: 5, assists: 3 },
          { name: "Aymen Ben Mohamed12", nationality: "Tunisia", age: 28, position: "Defender", goals: 1, assists: 2 },
        ],
        homeMatches: [
          { opponent: "ES Métlaoui", date: new Date("2022-01-15"), goalsFor: 1, goalsAgainst: 2 },
          { opponent: "AS Rejiche", date: new Date("2022-02-20"), goalsFor: 2, goalsAgainst: 1 },
          { opponent: "Stade Tunisien", date: new Date("2022-03-10"), goalsFor: 0, goalsAgainst: 3 },
        ],
        awayMatches: [
          { opponent: "CA Bizertin", date: new Date("2022-01-22"), goalsFor: 1, goalsAgainst: 2 },
          { opponent: "Espérance Sportive de Tunis", date: new Date("2022-02-27"), goalsFor: 0, goalsAgainst: 3 },
          { opponent: "Étoile Sportive du Sahel", date: new Date("2022-03-17"), goalsFor: 1, goalsAgainst: 1 },
        ],
      },
    ];
  
    for (const team of teams) {
      const createdTeam = await prisma.team.upsert({
        where: { name: team.name },
        update: {
          founded: team.founded,
          city: team.city,
          points: team.points,
          position: team.position,
          matchesPlayed: team.matchesPlayed,
          wins: team.wins,
          draws: team.draws,
          losses: team.losses,
          goalsFor: team.goalsFor,
          goalsAgainst: team.goalsAgainst,
          goalDifference: team.goalDifference,
        },
        create: {
          name: team.name,
          founded: team.founded,
          city: team.city,
          points: team.points,
          position: team.position,
          matchesPlayed: team.matchesPlayed,
          wins: team.wins,
          draws: team.draws,
          losses: team.losses,
          goalsFor: team.goalsFor,
          goalsAgainst: team.goalsAgainst,
          goalDifference: team.goalDifference,
        },
      });
  
      for (const player of team.players) {
        await prisma.player.upsert({
          where: { name: player.name },
          update: {
            nationality: player.nationality,
            age: player.age,
            position: player.position,
            goals: player.goals,
            assists: player.assists,
            team_id: createdTeam.id,
          },
          create: {
            name: player.name,
            nationality: player.nationality,
            age: player.age,
            position: player.position,
            goals: player.goals,
            assists: player.assists,
            team_id: createdTeam.id,
          },
        });
      }
  
      for (const match of team.homeMatches) {
        await prisma.match.create({
          data: {
            home_team_id: createdTeam.id,
            away_team_id: (await prisma.team.findUnique({ where: { name: match.opponent } })).id,
            date: match.date,
            homeGoals: match.goalsFor,
            awayGoals: match.goalsAgainst,
          },
        });
      }
  
      for (const match of team.awayMatches) {
        await prisma.match.create({
          data: {
            home_team_id: (await prisma.team.findUnique({ where: { name: match.opponent } })).id,
            away_team_id: createdTeam.id,
            date: match.date,
            awayGoals: match.goalsFor,
            homeGoals: match.goalsAgainst,
          },
        });
      }
  
      console.log(`Created or updated team: ${createdTeam.name}`);
    }
  }
  
  main()
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });